In [15]:
pip install escher

Requirement already satisfied: escher in /usr/local/lib/python3.6/dist-packages (1.7.3)
Requirement already satisfied: pytest<5,>=4.0.1 in /usr/local/lib/python3.6/dist-packages (from escher) (4.6.7)
Requirement already satisfied: Jinja2<3,>=2.7.3 in /usr/local/lib/python3.6/dist-packages (from escher) (2.10.3)
Requirement already satisfied: jsonschema<4,>=3.0.1 in /usr/local/lib/python3.6/dist-packages (from escher) (3.2.0)
Requirement already satisfied: pandas>=0.18 in /usr/local/lib/python3.6/dist-packages (from escher) (0.25.3)
Requirement already satisfied: cobra>=0.5.0 in /usr/local/lib/python3.6/dist-packages (from escher) (0.17.1)
Requirement already satisfied: ipywidgets<8,>=7.4.0 in /usr/local/lib/python3.6/dist-packages (from escher) (7.5.1)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.6/dist-packages (from pytest<5,>=4.0.1->escher) (1.12.0)
Requirement already satisfied: py>=1.5.0 in /usr/local/lib/python3.6/dist-packages (from pytest<5,>=4.0.1->escher) (1.8.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.6/dist-packages (from pytest<5,>=4.0.1->escher) (0.1.7)
Requirement already satisfied: importlib-metadata>=0.12; python_version < "3.8" in /usr/local/lib/python3.6/dist-packages (from pytest<5,>=4.0.1->escher) (1.3.0)
Requirement already satisfied: more-itertools>=4.0.0; python_version > "2.7" in /usr/local/lib/python3.6/dist-packages (from pytest<5,>=4.0.1->escher) (8.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.6/dist-packages (from pytest<5,>=4.0.1->escher) (19.2)
Requirement already satisfied: atomicwrites>=1.0 in /usr/local/lib/python3.6/dist-packages (from pytest<5,>=4.0.1->escher) (1.3.0)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.6/dist-packages (from pytest<5,>=4.0.1->escher) (19.3.0)
Requirement already satisfied: pluggy<1.0,>=0.12 in /usr/local/lib/python3.6/dist-packages (from pytest<5,>=4.0.1->escher) (0.13.1)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.6/dist-packages (from Jinja2<3,>=2.7.3->escher) (1.1.1)
Requirement already satisfied: pyrsistent>=0.14.0 in /usr/local/lib/python3.6/dist-packages (from jsonschema<4,>=3.0.1->escher) (0.15.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from jsonschema<4,>=3.0.1->escher) (42.0.2)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.18->escher) (2018.9)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.18->escher) (2.6.1)
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.18->escher) (1.17.4)
Requirement already satisfied: ruamel.yaml>=0.16 in /usr/local/lib/python3.6/dist-packages (from cobra>=0.5.0->escher) (0.16.5)
Requirement already satisfied: optlang>=1.4.2 in /usr/local/lib/python3.6/dist-packages (from cobra>=0.5.0->escher) (1.4.4)
Requirement already satisfied: python-libsbml-experimental==5.18.0 in /usr/local/lib/python3.6/dist-packages (from cobra>=0.5.0->escher) (5.18.0)
Requirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from cobra>=0.5.0->escher) (0.16.0)
Requirement already satisfied: swiglpk in /usr/local/lib/python3.6/dist-packages (from cobra>=0.5.0->escher) (4.65.0)
Requirement already satisfied: depinfo in /usr/local/lib/python3.6/dist-packages (from cobra>=0.5.0->escher) (1.5.1)
Requirement already satisfied: nbformat>=4.2.0 in /usr/local/lib/python3.6/dist-packages (from ipywidgets<8,>=7.4.0->escher) (4.4.0)
Requirement already satisfied: traitlets>=4.3.1 in /usr/local/lib/python3.6/dist-packages (from ipywidgets<8,>=7.4.0->escher) (4.3.3)
Requirement already satisfied: ipython>=4.0.0; python_version >= "3.3" in /usr/local/lib/python3.6/dist-packages (from ipywidgets<8,>=7.4.0->escher) (5.5.0)
Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.6/dist-packages (from ipywidgets<8,>=7.4.0->escher) (4.6.1)
Requirement already satisfied: widgetsnbextension~=3.5.0 in /usr/local/lib/python3.6/dist-packages (from ipywidgets<8,>=7.4.0->escher) (3.5.1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.6/dist-packages (from importlib-metadata>=0.12; python_version < "3.8"->pytest<5,>=4.0.1->escher) (0.6.0)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.6/dist-packages (from packaging->pytest<5,>=4.0.1->escher) (2.4.5)
Requirement already satisfied: ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.8" in /usr/local/lib/python3.6/dist-packages (from ruamel.yaml>=0.16->cobra>=0.5.0->escher) (0.2.0)
Requirement already satisfied: sympy>=1.0.0 in /usr/local/lib/python3.6/dist-packages (from optlang>=1.4.2->cobra>=0.5.0->escher) (1.1.1)
Requirement already satisfied: pipdeptree>=0.13.2 in /usr/local/lib/python3.6/dist-packages (from depinfo->cobra>=0.5.0->escher) (0.13.2)
Requirement already satisfied: jupyter-core in /usr/local/lib/python3.6/dist-packages (from nbformat>=4.2.0->ipywidgets<8,>=7.4.0->escher) (4.6.1)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.6/dist-packages (from nbformat>=4.2.0->ipywidgets<8,>=7.4.0->escher) (0.2.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.6/dist-packages (from traitlets>=4.3.1->ipywidgets<8,>=7.4.0->escher) (4.4.1)
Requirement already satisfied: pexpect; sys_platform != "win32" in /usr/local/lib/python3.6/dist-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets<8,>=7.4.0->escher) (4.7.0)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in /usr/local/lib/python3.6/dist-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets<8,>=7.4.0->escher) (1.0.18)
Requirement already satisfied: simplegeneric>0.8 in /usr/local/lib/python3.6/dist-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets<8,>=7.4.0->escher) (0.8.1)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.6/dist-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets<8,>=7.4.0->escher) (0.7.5)
Requirement already satisfied: pygments in /usr/local/lib/python3.6/dist-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets<8,>=7.4.0->escher) (2.1.3)
Requirement already satisfied: tornado>=4.0 in /usr/local/lib/python3.6/dist-packages (from ipykernel>=4.5.1->ipywidgets<8,>=7.4.0->escher) (4.5.3)
Requirement already satisfied: jupyter-client in /usr/local/lib/python3.6/dist-packages (from ipykernel>=4.5.1->ipywidgets<8,>=7.4.0->escher) (5.3.4)
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.6/dist-packages (from widgetsnbextension~=3.5.0->ipywidgets<8,>=7.4.0->escher) (5.2.2)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.6/dist-packages (from sympy>=1.0.0->optlang>=1.4.2->cobra>=0.5.0->escher) (1.1.0)
Requirement already satisfied: pip>=6.0.0 in /usr/local/lib/python3.6/dist-packages (from pipdeptree>=0.13.2->depinfo->cobra>=0.5.0->escher) (19.3.1)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.6/dist-packages (from pexpect; sys_platform != "win32"->ipython>=4.0.0; python_version >= "3.3"->ipywidgets<8,>=7.4.0->escher) (0.6.0)
Requirement already satisfied: pyzmq>=13 in /usr/local/lib/python3.6/dist-packages (from jupyter-client->ipykernel>=4.5.1->ipywidgets<8,>=7.4.0->escher) (17.0.0)
Requirement already satisfied: nbconvert in /usr/local/lib/python3.6/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7.4.0->escher) (5.6.1)
Requirement already satisfied: terminado>=0.3.3; sys_platform != "win32" in /usr/local/lib/python3.6/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7.4.0->escher) (0.8.3)
Requirement already satisfied: bleach in /usr/local/lib/python3.6/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7.4.0->escher) (3.1.0)
Requirement already satisfied: mistune<2,>=0.8.1 in /usr/local/lib/python3.6/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7.4.0->escher) (0.8.4)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.6/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7.4.0->escher) (1.4.2)
Requirement already satisfied: entrypoints>=0.2.2 in /usr/local/lib/python3.6/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7.4.0->escher) (0.3)
Requirement already satisfied: testpath in /usr/local/lib/python3.6/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7.4.0->escher) (0.4.4)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.6/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7.4.0->escher) (0.6.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.6/dist-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7.4.0->escher) (0.5.1)

In [16]:
pip install "cobra[all]"

Requirement already satisfied: cobra[all] in /usr/local/lib/python3.6/dist-packages (0.17.1)
Requirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from cobra[all]) (0.16.0)
Requirement already satisfied: optlang>=1.4.2 in /usr/local/lib/python3.6/dist-packages (from cobra[all]) (1.4.4)
Requirement already satisfied: ruamel.yaml>=0.16 in /usr/local/lib/python3.6/dist-packages (from cobra[all]) (0.16.5)
Requirement already satisfied: pandas>=0.17.0 in /usr/local/lib/python3.6/dist-packages (from cobra[all]) (0.25.3)
Requirement already satisfied: depinfo in /usr/local/lib/python3.6/dist-packages (from cobra[all]) (1.5.1)
Requirement already satisfied: python-libsbml-experimental==5.18.0 in /usr/local/lib/python3.6/dist-packages (from cobra[all]) (5.18.0)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from cobra[all]) (1.12.0)
Requirement already satisfied: swiglpk in /usr/local/lib/python3.6/dist-packages (from cobra[all]) (4.65.0)
Requirement already satisfied: numpy>=1.13 in /usr/local/lib/python3.6/dist-packages (from cobra[all]) (1.17.4)
Requirement already satisfied: scipy; extra == "all" in /usr/local/lib/python3.6/dist-packages (from cobra[all]) (1.3.3)
Requirement already satisfied: sympy>=1.0.0 in /usr/local/lib/python3.6/dist-packages (from optlang>=1.4.2->cobra[all]) (1.1.1)
Requirement already satisfied: ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.8" in /usr/local/lib/python3.6/dist-packages (from ruamel.yaml>=0.16->cobra[all]) (0.2.0)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.17.0->cobra[all]) (2.6.1)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.17.0->cobra[all]) (2018.9)
Requirement already satisfied: pipdeptree>=0.13.2 in /usr/local/lib/python3.6/dist-packages (from depinfo->cobra[all]) (0.13.2)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.6/dist-packages (from sympy>=1.0.0->optlang>=1.4.2->cobra[all]) (1.1.0)
Requirement already satisfied: pip>=6.0.0 in /usr/local/lib/python3.6/dist-packages (from pipdeptree>=0.13.2->depinfo->cobra[all]) (19.3.1)

In [0]:
from __future__ import print_function
import escher
from escher import Builder
import cobra
from time import sleep
import cobra.test

In [0]:
#Function for Output solution
def  output_solution(solution):
     print('Growth Rate (1/h): ' + str(solution.get_primal_by_id("BIOMASS_Ec_iJO1366_WT_53p95M")))
     print('Lycopene Production Rate (mmol/gdcw/h): ' + str(solution.get_primal_by_id('LYCO-dem')))
     print('Lycopene Yield (mol/mol glucose): ' + str(-solution.get_primal_by_id('LYCO-dem')/solution.get_primal_by_id('EX_glc__D_e')))

### Suggested workflow

### 1. Set up a model for the wild type E. coli strain used in the paper.

In [0]:
#Load the model for genome scale E. coli iJO1366
model = cobra.test.create_test_model("ecoli")
#model.optimize

#Set constraints for aerobic growth in glucose minimal media
model.reactions.get_by_id( "EX_glc__D_e").lower_bound= -10
model.reactions.get_by_id( "EX_o2_e").lower_bound = -15

**Visualization**

In [20]:
builder = Builder()
solution = model.optimize()
builder.map_name = 'iJO1366.Central metabolism'
builder.model_name = 'e_coli_core'
builder.reaction_data = solution.fluxes
builder.metabolite_data = solution.shadow_prices
builder.hide_secondary_metabolites = True

Downloading Map from https://escher.github.io/1-0-0/6/maps/Escherichia%20coli/iJO1366.Central%20metabolism.json
Downloading Model from https://escher.github.io/1-0-0/6/models/Escherichia%20coli/e_coli_core.json

In [0]:
builder.reaction_scale = [
    { 'type': 'min' , 'color' : '#000000' , 'size' : 12},
      { 'type': 'median' , 'color' : '#ffffff' , 'size' : 20},
        { 'type': 'max' , 'color' : '#ff0000' , 'size' : 25},
    ]
builder.reaction_scale_preset = 'GaBuRd'
builder.save_html("example_map.html")

In [22]:
print(model.reactions)

[<Reaction DM_4crsol_c at 0x7f74ba043e48>, <Reaction DM_5drib_c at 0x7f74ba043f28>, <Reaction DM_aacald_c at 0x7f74ba044240>, <Reaction DM_amob_c at 0x7f74ba044390>, <Reaction DM_mththf_c at 0x7f74ba044470>, <Reaction DM_oxam_c at 0x7f74ba0445c0>, <Reaction BIOMASS_Ec_iJO1366_WT_53p95M at 0x7f74ba0446a0>, <Reaction BIOMASS_Ec_iJO1366_core_53p95M at 0x7f74ba0447f0>, <Reaction EX_12ppd__R_e at 0x7f74ba04fcc0>, <Reaction EX_12ppd__S_e at 0x7f74ba044cf8>, <Reaction EX_14glucan_e at 0x7f74ba044cc0>, <Reaction EX_15dap_e at 0x7f74ba044dd8>, <Reaction EX_23camp_e at 0x7f74ba044eb8>, <Reaction EX_23ccmp_e at 0x7f74ba046278>, <Reaction EX_23cgmp_e at 0x7f74ba046048>, <Reaction EX_23cump_e at 0x7f74ba0461d0>, <Reaction EX_23dappa_e at 0x7f74ba0465c0>, <Reaction EX_26dap__M_e at 0x7f74ba046358>, <Reaction EX_2ddglcn_e at 0x7f74ba0465f8>, <Reaction EX_34dhpac_e at 0x7f74ba057940>, <Reaction EX_3amp_e at 0x7f74ba057a20>, <Reaction EX_3cmp_e at 0x7f74ba057b38>, <Reaction EX_3gmp_e at 0x7f74ba057c88>, <Reaction EX_3hcinnm_e at 0x7f74ba057da0>, <Reaction EX_3hpp_e at 0x7f74ba057eb8>, <Reaction EX_3hpppn_e at 0x7f74ba057f98>, <Reaction EX_3ump_e at 0x7f74ba05b128>, <Reaction EX_4abut_e at 0x7f74ba05b208>, <Reaction EX_4hoxpacd_e at 0x7f74ba05b358>, <Reaction EX_5dglcn_e at 0x7f74ba05b470>, <Reaction EX_5mtr_e at 0x7f74ba05b518>, <Reaction EX_LalaDglu_e at 0x7f74ba05b630>, <Reaction EX_LalaDgluMdap_e at 0x7f74ba05b780>, <Reaction EX_LalaDgluMdapDala_e at 0x7f74ba05b828>, <Reaction EX_LalaLglu_e at 0x7f74ba05b908>, <Reaction EX_ac_e at 0x7f74ba05bb00>, <Reaction EX_acac_e at 0x7f74ba05bac8>, <Reaction EX_acald_e at 0x7f74ba05bc50>, <Reaction EX_acgal_e at 0x7f74ba05bd68>, <Reaction EX_acgal1p_e at 0x7f74ba05be80>, <Reaction EX_acgam_e at 0x7f74ba05bf98>, <Reaction EX_acgam1p_e at 0x7f74b9fdd0b8>, <Reaction EX_acmana_e at 0x7f74b9fdd208>, <Reaction EX_acmum_e at 0x7f74b9fdd2e8>, <Reaction EX_acnam_e at 0x7f74b9fdd400>, <Reaction EX_acolipa_e at 0x7f74b9fdd550>, <Reaction EX_acser_e at 0x7f74b9fdd668>, <Reaction EX_ade_e at 0x7f74b9fdd748>, <Reaction EX_adn_e at 0x7f74b9fdd898>, <Reaction EX_adocbl_e at 0x7f74b9fdd9b0>, <Reaction EX_ag_e at 0x7f74b9fddbe0>, <Reaction EX_agm_e at 0x7f74b9fddba8>, <Reaction EX_akg_e at 0x7f74b9fddd30>, <Reaction EX_ala_B_e at 0x7f74b9fdde48>, <Reaction EX_ala__D_e at 0x7f74b9fddf60>, <Reaction EX_ala__L_e at 0x7f74b9fdf0b8>, <Reaction EX_alaala_e at 0x7f74b9fdf198>, <Reaction EX_all__D_e at 0x7f74b9fdf2b0>, <Reaction EX_alltn_e at 0x7f74b9fdf3c8>, <Reaction EX_amp_e at 0x7f74b9fdf4e0>, <Reaction EX_anhgm_e at 0x7f74b9fdf630>, <Reaction EX_arab__L_e at 0x7f74b9fdf748>, <Reaction EX_arbt_e at 0x7f74b9fdf860>, <Reaction EX_arbtn_e at 0x7f74b9fdf940>, <Reaction EX_arbtn_fe3_e at 0x7f74b9fdfa90>, <Reaction EX_arg__L_e at 0x7f74b9fdfba8>, <Reaction EX_ascb__L_e at 0x7f74b9fdfc50>, <Reaction EX_asn__L_e at 0x7f74b9fdfd68>, <Reaction EX_aso3_e at 0x7f74b9fdfe80>, <Reaction EX_asp__L_e at 0x7f74b9fdff98>, <Reaction EX_btn_e at 0x7f74b9fe1128>, <Reaction EX_but_e at 0x7f74b9fe1208>, <Reaction EX_butso3_e at 0x7f74b9fe1358>, <Reaction EX_ca2_e at 0x7f74b9fe1470>, <Reaction EX_cbi_e at 0x7f74b9fe1550>, <Reaction EX_cbl1_e at 0x7f74b9fe16a0>, <Reaction EX_cd2_e at 0x7f74b9fe17b8>, <Reaction EX_cgly_e at 0x7f74b9fe18d0>, <Reaction EX_chol_e at 0x7f74b9fe19e8>, <Reaction EX_chtbs_e at 0x7f74b9fe1b00>, <Reaction EX_cit_e at 0x7f74b9fe1c18>, <Reaction EX_cl_e at 0x7f74b9fe1e80>, <Reaction EX_cm_e at 0x7f74b9fe1fd0>, <Reaction EX_cmp_e at 0x7f74b9fe1f98>, <Reaction EX_co2_e at 0x7f74b9fe4128>, <Reaction EX_cobalt2_e at 0x7f74b9fe4240>, <Reaction EX_colipa_e at 0x7f74b9fe4358>, <Reaction EX_colipap_e at 0x7f74b9fe4438>, <Reaction EX_cpgn_e at 0x7f74b9fe4550>, <Reaction EX_cpgn_un_e at 0x7f74b9fe4668>, <Reaction EX_crn_e at 0x7f74b9fe47b8>, <Reaction EX_crn__D_e at 0x7f74b9fe4898>, <Reaction EX_csn_e at 0x7f74b9fe49e8>, <Reaction EX_cu_e at 0x7f74b9fe4c50>, <Reaction EX_cu2_e at 0x7f74b9fe4c18>, <Reaction EX_cyan_e at 0x7f74b9fe4d68>, <Reaction EX_cynt_e at 0x7f74b9fe4e80>, <Reaction EX_cys__D_e at 0x7f74b9fe4f98>, <Reaction EX_cys__L_e at 0x7f74b9fe60f0>, <Reaction EX_cytd_e at 0x7f74b9fe61d0>, <Reaction EX_dad_2_e at 0x7f74b9fe62e8>, <Reaction EX_damp_e at 0x7f74b9fe6438>, <Reaction EX_dca_e at 0x7f74b9fe6550>, <Reaction EX_dcmp_e at 0x7f74b9fe6668>, <Reaction EX_dcyt_e at 0x7f74b9fe6780>, <Reaction EX_ddca_e at 0x7f74b9fe6898>, <Reaction EX_dgmp_e at 0x7f74b9fe69b0>, <Reaction EX_dgsn_e at 0x7f74b9fe6ac8>, <Reaction EX_dha_e at 0x7f74b9fe6be0>, <Reaction EX_dimp_e at 0x7f74b9fe6cf8>, <Reaction EX_din_e at 0x7f74b9fe6e10>, <Reaction EX_dms_e at 0x7f74b9fe6f28>, <Reaction EX_dmso_e at 0x7f74b9fe8080>, <Reaction EX_dopa_e at 0x7f74b9fe8198>, <Reaction EX_doxrbcn_e at 0x7f74b9fe82b0>, <Reaction EX_dtmp_e at 0x7f74b9fe83c8>, <Reaction EX_dump_e at 0x7f74b9fe84a8>, <Reaction EX_duri_e at 0x7f74b9fe85f8>, <Reaction EX_eca4colipa_e at 0x7f74b9fe8710>, <Reaction EX_enlipa_e at 0x7f74b9fe8828>, <Reaction EX_enter_e at 0x7f74b9fe88d0>, <Reaction EX_etha_e at 0x7f74b9fe89e8>, <Reaction EX_ethso3_e at 0x7f74b9fe8b38>, <Reaction EX_etoh_e at 0x7f74b9fe8c50>, <Reaction EX_f6p_e at 0x7f74b9fe8d30>, <Reaction EX_fald_e at 0x7f74b9fe8e80>, <Reaction EX_fe2_e at 0x7f74b9fe8f98>, <Reaction EX_fe3_e at 0x7f74b9fea0f0>, <Reaction EX_fe3dcit_e at 0x7f74b9fea208>, <Reaction EX_fe3dhbzs_e at 0x7f74b9fea320>, <Reaction EX_fe3hox_e at 0x7f74b9fea400>, <Reaction EX_fe3hox_un_e at 0x7f74b9fea4e0>, <Reaction EX_fecrm_e at 0x7f74b9fea5f8>, <Reaction EX_fecrm_un_e at 0x7f74b9fea6d8>, <Reaction EX_feenter_e at 0x7f74b9fea828>, <Reaction EX_feoxam_e at 0x7f74b9fea8d0>, <Reaction EX_feoxam_un_e at 0x7f74b9fea9e8>, <Reaction EX_for_e at 0x7f74b9feab00>, <Reaction EX_fru_e at 0x7f74b9feabe0>, <Reaction EX_frulys_e at 0x7f74b9fead30>, <Reaction EX_fruur_e at 0x7f74b9feae48>, <Reaction EX_fuc__L_e at 0x7f74b9feaf28>, <Reaction EX_fum_e at 0x7f74b9fed0b8>, <Reaction EX_fusa_e at 0x7f74b9fed198>, <Reaction EX_g1p_e at 0x7f74b9fed2e8>, <Reaction EX_g3pc_e at 0x7f74b9fed400>, <Reaction EX_g3pe_e at 0x7f74b9fed518>, <Reaction EX_g3pg_e at 0x7f74b9fed630>, <Reaction EX_g3pi_e at 0x7f74b9fed748>, <Reaction EX_g3ps_e at 0x7f74b9fed860>, <Reaction EX_g6p_e at 0x7f74b9fed978>, <Reaction EX_gal_e at 0x7f74b9feda90>, <Reaction EX_gal_bD_e at 0x7f74b9fedba8>, <Reaction EX_gal1p_e at 0x7f74b9fedcc0>, <Reaction EX_galct__D_e at 0x7f74b9fedda0>, <Reaction EX_galctn__D_e at 0x7f74b9fedef0>, <Reaction EX_galctn__L_e at 0x7f74b9fedf98>, <Reaction EX_galt_e at 0x7f74b9ff00b8>, <Reaction EX_galur_e at 0x7f74b9ff0198>, <Reaction EX_gam_e at 0x7f74b9ff02e8>, <Reaction EX_gam6p_e at 0x7f74b9ff0400>, <Reaction EX_gbbtn_e at 0x7f74b9ff0518>, <Reaction EX_gdp_e at 0x7f74b9ff0630>, <Reaction EX_glc__D_e at 0x7f74b9ff0748>, <Reaction EX_glcn_e at 0x7f74b9ff0860>, <Reaction EX_glcr_e at 0x7f74b9ff0940>, <Reaction EX_glcur_e at 0x7f74b9ff0a90>, <Reaction EX_glcur1p_e at 0x7f74b9ff0ba8>, <Reaction EX_gln__L_e at 0x7f74b9ff0cc0>, <Reaction EX_glu__L_e at 0x7f74b9ff0da0>, <Reaction EX_gly_e at 0x7f74b9ff0eb8>, <Reaction EX_glyald_e at 0x7f74b9ff0fd0>, <Reaction EX_glyb_e at 0x7f74b9ff2160>, <Reaction EX_glyc_e at 0x7f74b9ff2240>, <Reaction EX_glyc__R_e at 0x7f74b9ff2390>, <Reaction EX_glyc2p_e at 0x7f74b9ff24a8>, <Reaction EX_glyc3p_e at 0x7f74b9ff2588>, <Reaction EX_glyclt_e at 0x7f74b9ff26a0>, <Reaction EX_gmp_e at 0x7f74b9ff27b8>, <Reaction EX_gsn_e at 0x7f74b9ff28d0>, <Reaction EX_gthox_e at 0x7f74b9ff2a20>, <Reaction EX_gthrd_e at 0x7f74b9ff2b38>, <Reaction EX_gtp_e at 0x7f74b9ff2c50>, <Reaction EX_gua_e at 0x7f74b9ff2d68>, <Reaction EX_h_e at 0x7f74b9ff2fd0>, <Reaction EX_h2_e at 0x7f74b9ff4128>, <Reaction EX_h2o_e at 0x7f74b9ff40f0>, <Reaction EX_h2o2_e at 0x7f74b9ff4240>, <Reaction EX_h2s_e at 0x7f74b9ff4358>, <Reaction EX_hacolipa_e at 0x7f74b9ff4470>, <Reaction EX_halipa_e at 0x7f74b9ff4588>, <Reaction EX_hdca_e at 0x7f74b9ff4630>, <Reaction EX_hdcea_e at 0x7f74b9ff4748>, <Reaction EX_hg2_e at 0x7f74b9ff4898>, <Reaction EX_his__L_e at 0x7f74b9ff49b0>, <Reaction EX_hom__L_e at 0x7f74b9ff4ac8>, <Reaction EX_hxa_e at 0x7f74b9ff4ba8>, <Reaction EX_hxan_e at 0x7f74b9ff4cc0>, <Reaction EX_idon__L_e at 0x7f74b9ff4e10>, <Reaction EX_ile__L_e at 0x7f74b9ff4f28>, <Reaction EX_imp_e at 0x7f74b9ff7048>, <Reaction EX_indole_e at 0x7f74b9ff7160>, <Reaction EX_inost_e at 0x7f74b9ff72b0>, <Reaction EX_ins_e at 0x7f74b9ff7390>, <Reaction EX_isetac_e at 0x7f74b9ff74e0>, <Reaction EX_k_e at 0x7f74b9ff7710>, <Reaction EX_kdo2lipid4_e at 0x7f74b9ff76d8>, <Reaction EX_lac__D_e at 0x7f74b9ff7828>, <Reaction EX_lac__L_e at 0x7f74b9ff78d0>, <Reaction EX_lcts_e at 0x7f74b9ff79e8>, <Reaction EX_leu__L_e at 0x7f74b9ff7b00>, <Reaction EX_lipa_e at 0x7f74b9ff7c50>, <Reaction EX_lipa_cold_e at 0x7f74b9ff7d30>, <Reaction EX_lipoate_e at 0x7f74b9ff7e80>, <Reaction EX_lys__L_e at 0x7f74b9ff7f28>, <Reaction EX_lyx__L_e at 0x7f74b9ff9080>, <Reaction EX_mal__D_e at 0x7f74b9ff9198>, <Reaction EX_mal__L_e at 0x7f74b9ff92b0>, <Reaction EX_malt_e at 0x7f74b9ff93c8>, <Reaction EX_malthx_e at 0x7f74b9ff94e0>, <Reaction EX_maltpt_e at 0x7f74b9ff9630>, <Reaction EX_malttr_e at 0x7f74b9ff9710>, <Reaction EX_maltttr_e at 0x7f74b9ff9828>, <Reaction EX_man_e at 0x7f74b9ff9940>, <Reaction EX_man6p_e at 0x7f74b9ff9a58>, <Reaction EX_manglyc_e at 0x7f74b9ff9ba8>, <Reaction EX_melib_e at 0x7f74b9ff9cc0>, <Reaction EX_meoh_e at 0x7f74b9ff9da0>, <Reaction EX_met__D_e at 0x7f74b9ff9ef0>, <Reaction EX_met__L_e at 0x7f74b9ffb048>, <Reaction EX_metsox_R__L_e at 0x7f74b9ffb128>, <Reaction EX_metsox_S__L_e at 0x7f74b9ffb240>, <Reaction EX_mg2_e at 0x7f74b9ffb320>, <Reaction EX_mincyc_e at 0x7f74b9ffb400>, <Reaction EX_minohp_e at 0x7f74b9ffb550>, <Reaction EX_mmet_e at 0x7f74b9ffb630>, <Reaction EX_mn2_e at 0x7f74b9ffb748>, <Reaction EX_mnl_e at 0x7f74b9ffb898>, <Reaction EX_mobd_e at 0x7f74b9ffb9b0>, <Reaction EX_mso3_e at 0x7f74b9ffbac8>, <Reaction EX_n2o_e at 0x7f74b9ffbbe0>, <Reaction EX_na1_e at 0x7f74b9ffbcf8>, <Reaction EX_nac_e at 0x7f74b9ffbe10>, <Reaction EX_nh4_e at 0x7f74b9ffbf28>, <Reaction EX_ni2_e at 0x7f74b9fff080>, <Reaction EX_nmn_e at 0x7f74b9fff198>, <Reaction EX_no_e at 0x7f74b9fff400>, <Reaction EX_no2_e at 0x7f74b9fff3c8>, <Reaction EX_no3_e at 0x7f74b9fff518>, <Reaction EX_novbcn_e at 0x7f74b9fff630>, <Reaction EX_o16a4colipa_e at 0x7f74b9fff748>, <Reaction EX_o2_e at 0x7f74b9fff940>, <Reaction EX_o2s_e at 0x7f74b9fff908>, <Reaction EX_ocdca_e at 0x7f74b9fffa90>, <Reaction EX_ocdcea_e at 0x7f74b9fffba8>, <Reaction EX_octa_e at 0x7f74b9fffcc0>, <Reaction EX_orn_e at 0x7f74b9fffda0>, <Reaction EX_orot_e at 0x7f74b9fffef0>, <Reaction EX_pacald_e at 0x7f74ba000048>, <Reaction EX_peamn_e at 0x7f74ba000160>, <Reaction EX_phe__L_e at 0x7f74ba000240>, <Reaction EX_pheme_e at 0x7f74ba000390>, <Reaction EX_pi_e at 0x7f74ba0005f8>, <Reaction EX_pnto__R_e at 0x7f74ba0005c0>, <Reaction EX_ppa_e at 0x7f74ba000710>, <Reaction EX_ppal_e at 0x7f74ba0007f0>, <Reaction EX_pppn_e at 0x7f74ba000940>, <Reaction EX_ppt_e at 0x7f74ba000a58>, <Reaction EX_pro__L_e at 0x7f74ba000b70>, <Reaction EX_progly_e at 0x7f74ba000c88>, <Reaction EX_psclys_e at 0x7f74ba000d68>, <Reaction EX_pser__L_e at 0x7f74ba000e80>, <Reaction EX_ptrc_e at 0x7f74ba000f98>, <Reaction EX_pydam_e at 0x7f74ba0030f0>, <Reaction EX_pydx_e at 0x7f74ba003240>, <Reaction EX_pydxn_e at 0x7f74ba003358>, <Reaction EX_pyr_e at 0x7f74ba003470>, <Reaction EX_quin_e at 0x7f74ba003588>, <Reaction EX_r5p_e at 0x7f74ba0036a0>, <Reaction EX_rfamp_e at 0x7f74ba0037b8>, <Reaction EX_rib__D_e at 0x7f74ba0038d0>, <Reaction EX_rmn_e at 0x7f74ba0039e8>, <Reaction EX_sbt__D_e at 0x7f74ba003ac8>, <Reaction EX_sel_e at 0x7f74ba003c18>, <Reaction EX_ser__D_e at 0x7f74ba003cf8>, <Reaction EX_ser__L_e at 0x7f74ba003e48>, <Reaction EX_skm_e at 0x7f74ba003f28>, <Reaction EX_slnt_e at 0x7f74ba006080>, <Reaction EX_so2_e at 0x7f74ba0061d0>, <Reaction EX_so3_e at 0x7f74ba0062e8>, <Reaction EX_so4_e at 0x7f74ba006400>, <Reaction EX_spmd_e at 0x7f74ba006518>, <Reaction EX_succ_e at 0x7f74ba006630>, <Reaction EX_sucr_e at 0x7f74ba006748>, <Reaction EX_sulfac_e at 0x7f74ba006860>, <Reaction EX_tartr__D_e at 0x7f74ba006978>, <Reaction EX_tartr__L_e at 0x7f74ba006a58>, <Reaction EX_taur_e at 0x7f74ba006b38>, <Reaction EX_tcynt_e at 0x7f74ba006c18>, <Reaction EX_thm_e at 0x7f74ba006d68>, <Reaction EX_thr__L_e at 0x7f74ba006e80>, <Reaction EX_thrp_e at 0x7f74ba006f98>, <Reaction EX_thym_e at 0x7f74ba0090b8>, <Reaction EX_thymd_e at 0x7f74ba009208>, <Reaction EX_tma_e at 0x7f74ba009320>, <Reaction EX_tmao_e at 0x7f74ba009438>, <Reaction EX_tre_e at 0x7f74ba009550>, <Reaction EX_trp__L_e at 0x7f74ba009668>, <Reaction EX_tsul_e at 0x7f74ba009780>, <Reaction EX_ttdca_e at 0x7f74ba009860>, <Reaction EX_ttdcea_e at 0x7f74ba0099b0>, <Reaction EX_ttrcyc_e at 0x7f74ba009ac8>, <Reaction EX_tungs_e at 0x7f74ba009ba8>, <Reaction EX_tym_e at 0x7f74ba009cc0>, <Reaction EX_tyr__L_e at 0x7f74ba009e10>, <Reaction EX_tyrp_e at 0x7f74ba009f28>, <Reaction EX_uacgam_e at 0x7f74ba00b048>, <Reaction EX_udpacgal_e at 0x7f74ba00b198>, <Reaction EX_udpg_e at 0x7f74ba00b278>, <Reaction EX_udpgal_e at 0x7f74ba00b358>, <Reaction EX_udpglcur_e at 0x7f74ba00b4a8>, <Reaction EX_ump_e at 0x7f74ba00b588>, <Reaction EX_ura_e at 0x7f74ba00b668>, <Reaction EX_urea_e at 0x7f74ba00b7b8>, <Reaction EX_uri_e at 0x7f74ba00b8d0>, <Reaction EX_val__L_e at 0x7f74ba00b9e8>, <Reaction EX_xan_e at 0x7f74ba00bb00>, <Reaction EX_xmp_e at 0x7f74ba00bbe0>, <Reaction EX_xtsn_e at 0x7f74ba00bd30>, <Reaction EX_xyl__D_e at 0x7f74ba00be48>, <Reaction EX_xylu__L_e at 0x7f74ba00bf60>, <Reaction EX_zn2_e at 0x7f74ba00e080>, <Reaction 12DGR120tipp at 0x7f74ba00e198>, <Reaction 12DGR140tipp at 0x7f74ba00e2e8>, <Reaction 12DGR141tipp at 0x7f74ba00e438>, <Reaction 12DGR160tipp at 0x7f74ba00e5c0>, <Reaction 12DGR161tipp at 0x7f74ba00e748>, <Reaction 12DGR180tipp at 0x7f74ba00e8d0>, <Reaction 12DGR181tipp at 0x7f74ba00ea58>, <Reaction 12PPDRtex at 0x7f74ba00ebe0>, <Reaction 12PPDRtpp at 0x7f74ba00ed68>, <Reaction 12PPDStex at 0x7f74ba0100b8>, <Reaction 12PPDStpp at 0x7f74ba00ef28>, <Reaction 14GLUCANabcpp at 0x7f74ba00ef60>, <Reaction 14GLUCANtexi at 0x7f74ba0104a8>, <Reaction 23CAMPtex at 0x7f74ba010eb8>, <Reaction 23CCMPtex at 0x7f74ba010e48>, <Reaction 23CGMPtex at 0x7f74ba010cf8>, <Reaction 23CUMPtex at 0x7f74ba010dd8>, <Reaction 23DAPPAt2pp at 0x7f74ba011748>, <Reaction 23DAPPAtex at 0x7f74ba0119b0>, <Reaction 23PDE2pp at 0x7f74ba011940>, <Reaction 23PDE4pp at 0x7f74ba011ef0>, <Reaction 23PDE7pp at 0x7f74ba015550>, <Reaction 23PDE9pp at 0x7f74ba011e48>, <Reaction 26DAHtex at 0x7f74ba015518>, <Reaction 2AGPA120tipp at 0x7f74ba015a58>, <Reaction 2AGPA140tipp at 0x7f74ba015f60>, <Reaction 2AGPA141tipp at 0x7f74ba017898>, <Reaction 2AGPA160tipp at 0x7f74ba0175c0>, <Reaction 2AGPA161tipp at 0x7f74ba017828>, <Reaction 2AGPA180tipp at 0x7f74ba017a58>, <Reaction 2AGPA181tipp at 0x7f74ba017c50>, <Reaction 2AGPE120tipp at 0x7f74ba017e48>, <Reaction 2AGPE140tipp at 0x7f74ba01a080>, <Reaction 2AGPE141tipp at 0x7f74ba01a278>, <Reaction 2AGPE160tipp at 0x7f74ba01a470>, <Reaction 2AGPE161tipp at 0x7f74ba01a668>, <Reaction 2AGPE180tipp at 0x7f74ba01a860>, <Reaction 2AGPE181tipp at 0x7f74ba01aa58>, <Reaction 2AGPEAT120 at 0x7f74ba01ac50>, <Reaction 2AGPEAT140 at 0x7f74ba01ae48>, <Reaction 2AGPEAT141 at 0x7f74ba01b898>, <Reaction 2AGPEAT160 at 0x7f74ba01b278>, <Reaction 2AGPEAT161 at 0x7f74ba01b828>, <Reaction 2AGPEAT180 at 0x7f74ba01bcf8>, <Reaction 2AGPEAT181 at 0x7f74b9f9d198>, <Reaction 2AGPG120tipp at 0x7f74b9f9d6a0>, <Reaction 2AGPG140tipp at 0x7f74b9f9db38>, <Reaction 2AGPG141tipp at 0x7f74b9f9f048>, <Reaction 2AGPG160tipp at 0x7f74b9f9f4a8>, <Reaction 2AGPG161tipp at 0x7f74b9f9f5c0>, <Reaction 2AGPG180tipp at 0x7f74b9f9f7b8>, <Reaction 2AGPG181tipp at 0x7f74b9f9f9b0>, <Reaction 2AGPGAT120 at 0x7f74b9f9fba8>, <Reaction 2AGPGAT140 at 0x7f74b9f9fda0>, <Reaction 2AGPGAT141 at 0x7f74b9f9ff98>, <Reaction 2AGPGAT160 at 0x7f74b9fa31d0>, <Reaction 2AGPGAT161 at 0x7f74b9fa3780>, <Reaction 2AGPGAT180 at 0x7f74b9fa3c18>, <Reaction 2AGPGAT181 at 0x7f74b9fa50b8>, <Reaction 2DGULRGx at 0x7f74b9fa5588>, <Reaction 2DGULRGy at 0x7f74b9fa5a20>, <Reaction 2DGULRx at 0x7f74b9fa7be0>, <Reaction 2DGULRy at 0x7f74b9faa048>, <Reaction 2MAHMP at 0x7f74b9faa4a8>, <Reaction 34dhpactex at 0x7f74b9fa7b70>, <Reaction 3AMACHYD at 0x7f74b9faab00>, <Reaction 3AMPtex at 0x7f74b9fad470>, <Reaction 3CMPtex at 0x7f74b9fad668>, <Reaction 3GMPtex at 0x7f74b9fad940>, <Reaction 3HAD100 at 0x7f74b9fadc18>, <Reaction 3HAD120 at 0x7f74b9faf048>, <Reaction 3HAD121 at 0x7f74b9faf470>, <Reaction 3HAD140 at 0x7f74b9faf7b8>, <Reaction 3HAD141 at 0x7f74b9fafbe0>, <Reaction 3HAD160 at 0x7f74b9faff28>, <Reaction 3HAD161 at 0x7f74b9fb12e8>, <Reaction 3HAD180 at 0x7f74b9fb1630>, <Reaction 3HAD181 at 0x7f74b9fb1a58>, <Reaction 3HAD40 at 0x7f74b9fb1da0>, <Reaction 3HAD60 at 0x7f74b9fb30f0>, <Reaction 3HAD80 at 0x7f74b9fb34a8>, <Reaction 3HCINNMH at 0x7f74b9fb1cc0>, <Reaction 3HPPPNH at 0x7f74b9fb50b8>, <Reaction 3HPPtex at 0x7f74b9fb5828>, <Reaction 3HPPtpp at 0x7f74b9fb5b70>, <Reaction 3KGK at 0x7f74b9fb3fd0>, <Reaction 3NTD2pp at 0x7f74b9fb85c0>, <Reaction 3NTD4pp at 0x7f74b9fb8ba8>, <Reaction 3NTD7pp at 0x7f74b9fba198>, <Reaction 3NTD9pp at 0x7f74b9fba748>, <Reaction 3OAR100 at 0x7f74b9fbacf8>, <Reaction 3OAR120 at 0x7f74b9fbd278>, <Reaction 3OAR121 at 0x7f74b9fbd780>, <Reaction 3OAR140 at 0x7f74b9fbdc18>, <Reaction 3OAR141 at 0x7f74b9fc0198>, <Reaction 3OAR160 at 0x7f74b9fc0630>, <Reaction 3OAR161 at 0x7f74b9fc0b38>, <Reaction 3OAR180 at 0x7f74b9fc0fd0>, <Reaction 3OAR181 at 0x7f74b9fc14a8>, <Reaction 3OAR40 at 0x7f74b9fc1940>, <Reaction 3OAR60 at 0x7f74b9fc1dd8>, <Reaction 3OAR80 at 0x7f74b9fc3320>, <Reaction 3OAS100 at 0x7f74b9fc3860>, <Reaction 3OAS120 at 0x7f74b9fc3e10>, <Reaction 3OAS121 at 0x7f74b9fc63c8>, <Reaction 3OAS140 at 0x7f74b9fc68d0>, <Reaction 3OAS141 at 0x7f74b9fc6e80>, <Reaction 3OAS160 at 0x7f74b9fc7390>, <Reaction 3OAS161 at 0x7f74b9fc7908>, <Reaction 3OAS180 at 0x7f74b9fc7c88>, <Reaction 3OAS181 at 0x7f74b9fc7f98>, <Reaction 3OAS60 at 0x7f74b9fcb208>, <Reaction 3OAS80 at 0x7f74b9fcb4e0>, <Reaction 3OXCOAT at 0x7f74b9fcb780>, <Reaction 3PEPTabcpp at 0x7f74b9fc7dd8>, <Reaction 3PEPTtex at 0x7f74b9fcbac8>, <Reaction 3UMPtex at 0x7f74b9fcbe48>, <Reaction 42A12BOOXpp at 0x7f74b9fcbb70>, <Reaction 4HOXPACDtex at 0x7f74b9fc7eb8>, <Reaction 4HTHRS at 0x7f74b9fcd828>, <Reaction 4PCP at 0x7f74b9fcbf98>, <Reaction 4PCPpp at 0x7f74b9fcdef0>, <Reaction 4PEPTabcpp at 0x7f74b9fcdeb8>, <Reaction 4PEPTtex at 0x7f74b9fcde10>, <Reaction 5DGLCNR at 0x7f74b9fd0470>, <Reaction 5DGLCNt2rpp at 0x7f74b9fd0080>, <Reaction 5DGLCNtex at 0x7f74b9fd0a20>, <Reaction 5DOAN at 0x7f74b9fd0cc0>, <Reaction 5MTRtex at 0x7f74b9fd52b0>, <Reaction 5MTRtpp at 0x7f74b9fd54e0>, <Reaction A5PISO at 0x7f74b9fd0898>, <Reaction AACPS1 at 0x7f74b9fd57f0>, <Reaction AACPS2 at 0x7f74b9fd5710>, <Reaction AACPS3 at 0x7f74b9fd9128>, <Reaction AACPS4 at 0x7f74b9fd9400>, <Reaction AACPS5 at 0x7f74b9fd9668>, <Reaction AACPS6 at 0x7f74b9fd9898>, <Reaction AACPS7 at 0x7f74b9fd9b70>, <Reaction AACPS8 at 0x7f74b9fd9e48>, <Reaction AACPS9 at 0x7f74b9fdc128>, <Reaction AACTOOR at 0x7f74b9fdc438>, <Reaction AADDGT at 0x7f74b9fd9b38>, <Reaction AAMYL at 0x7f74b9fd9f60>, <Reaction AAMYLpp at 0x7f74b9fdcb70>, <Reaction AB6PGH at 0x7f74b9fdcd30>, <Reaction ABTA at 0x7f74b9fdccf8>, <Reaction ABUTD at 0x7f74b9f5f048>, <Reaction ABUTt2pp at 0x7f74b9f5f400>, <Reaction ABUTtex at 0x7f74b9f5fcc0>, <Reaction ACACCT at 0x7f74b9f5feb8>, <Reaction ACACT1r at 0x7f74b9f64390>, <Reaction ACACT2r at 0x7f74b9f64908>, <Reaction ACACT3r at 0x7f74b9f64d30>, <Reaction ACACT4r at 0x7f74b9f64f98>, <Reaction ACACT5r at 0x7f74b9f663c8>, <Reaction ACACT6r at 0x7f74b9f665f8>, <Reaction ACACT7r at 0x7f74b9f669e8>, <Reaction ACACT8r at 0x7f74b9f66e10>, <Reaction ACACt2pp at 0x7f74b9f64b70>, <Reaction ACACtex at 0x7f74b9f6a320>, <Reaction ACALD at 0x7f74b9f6a2e8>, <Reaction ACALDtex at 0x7f74b9f66e48>, <

### 2. Add the lycopene pathway to the model.

In [0]:
#Add crtEBI pathway for lycopene production
#Hint: see Alper et al 2005 Met Eng, Supp Info for reactions
#New metabolites: ggpp_c, phyto_c, lyco_c
from cobra import Metabolite
coa_c = model.metabolites.get_by_id( 'coa_c')
ipdp_c = model.metabolites.get_by_id( 'ipdp_c')
frdp_c = model.metabolites.get_by_id( 'frdp_c')
ppi_c = model.metabolites.get_by_id( 'ppi_c')
nadp_c = model.metabolites.get_by_id( 'nadp_c')
nadph_c = model.metabolites.get_by_id( 'nadph_c')

#Create new metabolites
ggpp_c = Metabolite( 'ggpp_c', formula='C20H36O7P2', name='Geranylgeranyl Pyrophospate', compartment ='c')
phyto_c = Metabolite( 'phyto_c', formula='C40H64', name='Phytoene', compartment ='c')
lyco_c = Metabolite( 'lyco_c', formula='C40H56', name='Lycopene', compartment ='c')

In [0]:
#New reactions: CRTE, CRTB, CRTI, LYCO-dem
from cobra import Reaction
#add CRTE:
reaction1 = Reaction('CRTE')
reaction1.name = 'Geranylgeranyl diphosphate (GGPP) synthase'
reaction1.subsystem = 'Lycopene biosynthesis'
reaction1.lower_bound = 0
reaction1.upper_bound = 1000
reaction1.add_metabolites({ipdp_c: -1.0, frdp_c: -1.0, ggpp_c: 1.0, ppi_c: 1.0})
model.add_reaction(reaction1)

#add CRTB:
reaction2 = Reaction('CRTB')
reaction2.name = 'Phytoene synthase'
reaction2.subsystem = 'Lycopene biosynthesis'
reaction2.lower_bound = 0
reaction2.upper_bound = 1000
reaction2.add_metabolites({ggpp_c: -2.0, phyto_c: 1.0, ppi_c: 1.0})
model.add_reaction(reaction2)

#add CRTI:
reaction3 = Reaction('CRTI')
reaction3.name = 'Phytoene desaturase'
reaction3.subsystem = 'Lycopene biosynthesis'
reaction3.lower_bound = 0
reaction3.upper_bound = 1000
reaction3.add_metabolites({phyto_c: -1.0, nadp_c: -8.0, lyco_c: 1.0, nadph_c: 8.0})
model.add_reaction(reaction3)

#add LYCO-dem:
reaction4 = Reaction('LYCO-dem')
reaction4.name = 'Lycopene demand'
reaction4.subsystem = 'Lycopene biosynthesis'
reaction4.lower_bound = 0
reaction4.upper_bound = 1000
reaction4.add_metabolites({lyco_c: -1.0})
model.add_reaction(reaction4)

In [0]:
#objective function
model.reactions.get_by_id('BIOMASS_Ec_iJO1366_core_53p95M').objective_coefficient = 0
model.reactions.get_by_id('BIOMASS_Ec_iJO1366_WT_53p95M').objective_coefficient = 1
model.reactions.get_by_id('LYCO-dem').objective_coefficient = 0.5

### 3. Simulate the model from Step 2

What objective function should you choose to answer the questions above?

In [0]:
# use for observing theoretical maximum yield of lycopene
model_1 = model.copy()

# use for knock_out+gene overexpression
model_2 = model.copy()

# use for knock_out
model_3 = model.copy()

# use for gene overexpression
model_4 = model.copy()

In [27]:
model_1.reactions.get_by_id('BIOMASS_Ec_iJO1366_core_53p95M').objective_coefficient = 0
model_1.reactions.get_by_id('BIOMASS_Ec_iJO1366_WT_53p95M').objective_coefficient = 1.0

#Solve
solution=model_1.optimize() #solution is stored at model.solution

#Output solution
output_solution(solution)

Growth Rate (1/h): 0.8168839340845325
Lycopene Production Rate (mmol/gdcw/h): 0.1909680042423488
Lycopene Yield (mol/mol glucose): 0.01909680042423488

Theoretical Maximum

In [28]:
#Set the objective to lycopene production
model_1.reactions.get_by_id('BIOMASS_Ec_iJO1366_core_53p95M').objective_coefficient = 0
model_1.reactions.get_by_id('BIOMASS_Ec_iJO1366_WT_53p95M').objective_coefficient = 0
model_1.reactions.get_by_id('LYCO-dem').objective_coefficient = 1.0

#Solve
solution = model_1.optimize()

#Output solution
output_solution(solution)

Growth Rate (1/h): 0.0
Lycopene Production Rate (mmol/gdcw/h): 1.1019165727170228
Lycopene Yield (mol/mol glucose): 0.11019165727170228

Wild type strain

In [29]:
model_1.reactions.get_by_id('BIOMASS_Ec_iJO1366_core_53p95M').objective_coefficient = 0
model_1.reactions.get_by_id('BIOMASS_Ec_iJO1366_WT_53p95M').objective_coefficient = 1
model_1.reactions.get_by_id('LYCO-dem').objective_coefficient = 0.5

#Solve
solution=model_1.optimize() #solution is stored at model.solution

#Output solution
output_solution(solution)

Growth Rate (1/h): 0.8168839340845268
Lycopene Production Rate (mmol/gdcw/h): 0.19096800424234786
Lycopene Yield (mol/mol glucose): 0.019096800424234787

### 4. Add gene knockouts from the paper to the lycopene model.

Which gene knockouts can we simulate? gdhA, aceE, ytjC(gmpB), fdhF

In [0]:
#Knockout genes gdhA, aceE, ytjC(gpmB), fdhF  get From  2005a
model_3.genes.b1761.knock_out() # gdhA
model_3.genes.b0114.knock_out() # aceE
model_3.genes.b4395.knock_out() # ytjC
model_3.genes.b4079.knock_out() # fdhF

### 5. Simulate the model from Step 4.

In [31]:
solution_3 = model_3.optimize()
output_solution(solution_3)

Growth Rate (1/h): 0.6907866633676604
Lycopene Production Rate (mmol/gdcw/h): 0.2950734841554434
Lycopene Yield (mol/mol glucose): 0.029507348415544338

In [32]:
model_3.summary()

### 6. Add gene overexpression to the lycopene model from Step 2.

gene name : dxs, idi , ispFD (ispF and ispD) reactions: DXPS, IPDDI, MECDPS, MEPCT

In [33]:
from cobra.flux_analysis import flux_variability_analysis
reactions_OE = [model_4.reactions.DXPS, model_4.reactions.IPDDI, model_4.reactions.MECDPS, model_4.reactions.MEPCT]
fva = flux_variability_analysis(model_4, reaction_list = reactions_OE, fraction_of_optimum=0.9,loopless=False)
print (fva)

         minimum   maximum
DXPS    0.005807  3.412359
IPDDI  -2.559498  0.852591
MECDPS  0.005441  3.412088
MEPCT   0.005441  3.412088

In [0]:
# Overexpress by setting lower bound is greater than  upper bound
model_4.reactions.get_by_id('DXPS').lower_bound = 4
model_4.reactions.get_by_id('IPDDI').lower_bound = 1.4
model_4.reactions.get_by_id('MECDPS').lower_bound = 4
model_4.reactions.get_by_id('MEPCT').lower_bound = 4

### 7. Simulate the model from Step 6.

In [36]:
solution_4 = model_4.optimize()
output_solution(solution_4)

Growth Rate (1/h): 0.3636282726175124
Lycopene Production Rate (mmol/gdcw/h): 0.6998278220129155
Lycopene Yield (mol/mol glucose): 0.06998278220129155

In [37]:
model_4.summary()

### 8. Create a lycopene-producing model with overexpression + knockouts.

In [38]:
reactions_OE = [model_2.reactions.DXPS, model_2.reactions.IPDDI, model_2.reactions.MECDPS, model_2.reactions.MEPCT]
fva = flux_variability_analysis(model_2, reaction_list = reactions_OE, fraction_of_optimum=0.9)
print (fva)

         minimum   maximum
DXPS    0.005807  3.412359
IPDDI  -2.559498  0.852591
MECDPS  0.005441  3.412088
MEPCT   0.005441  3.412088

In [0]:
#Overexpress dxs, idi, ispFD
model_2.reactions.get_by_id('DXPS').lower_bound = 4
model_2.reactions.get_by_id('IPDDI').lower_bound = 1.6
model_2.reactions.get_by_id('MECDPS').lower_bound = 4
model_2.reactions.get_by_id('MEPCT').lower_bound = 4

model_2.genes.b1761.knock_out() # gdhA
model_2.genes.b0114.knock_out() # aceA
model_2.genes.b4395.knock_out() # ytjC
model_2.genes.b4079.knock_out() # fdhF

### 9. Simulate the model from Step 8.

In [40]:
solution_2 = model_2.optimize()
output_solution(solution_2)

Growth Rate (1/h): 0.2641504320879474
Lycopene Production Rate (mmol/gdcw/h): 0.7998749247704064
Lycopene Yield (mol/mol glucose): 0.07998749247704065

In [41]:
model_2.summary()