### Extract metadata from new paper

In [2]:
!pip install pdfx

Collecting pdfx
  Downloading https://files.pythonhosted.org/packages/2f/82/926a2eef8023114c0f55f42cd5335c33676a8d8cfcd76571fd1cd1fc7189/pdfx-1.3.0-py2.py3-none-any.whl (80kB)
     |████████████████████████████████| 81kB 2.7MB/s
Collecting pdfminer2
  Downloading https://files.pythonhosted.org/packages/fa/97/bd2a2de878438c27ffd710b5d6562c7a0230b0f3ca86059ec635ed231eb1/pdfminer2-20151206-py2.py3-none-any.whl (117kB)
     |████████████████████████████████| 122kB 9.9MB/s
Requirement already satisfied: chardet in /usr/local/lib/python3.6/dist-packages (from pdfx) (3.0.4)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from pdfminer2->pdfx) (1.12.0)
Installing collected packages: pdfminer2, pdfx
Successfully installed pdfminer2-20151206 pdfx-1.3.0

In [0]:
import pdfx

pdf_1 = pdfx.PDFx('part2_paper1.pdf')
metadata_1 = pdf_1.get_metadata()

pdf_2 = pdfx.PDFx('part2_paper2.pdf')
metadata_2 = pdf_2.get_metadata()

In [0]:
metadata_1

In [58]:
metadata_2

{'Author': 'Sumaiya Dabeer',
 'CreationDate': 'D:20191223070950Z',
 'Creator': 'Elsevier',
 'Keywords': 'Histopathology image,Medical image processing,Convolutional neural network,Deep learning,Breast cancer',
 'ModDate': 'D:20191223071222Z',
 None: {'XlEDuztn8owuMzgmGmgqQnLNNmMqMlwiMotaGmt_.n.j_mtyNyMiQo9eOod-Kmd2LoduTma': None},
 'Pages': 9,
 'Producer': 'Acrobat Distiller 8.1.0 (Windows)',
 'Subject': 'Informatics in Medicine Unlocked, 16 (2019) 100231. doi:10.1016/j.imu.2019.100231',
 'Title': 'Cancer diagnosis in histopathological image: CNN based approach',
 'crossmark': {'CrossMarkDomains': ['elsevier.com', 'sciencedirect.com'],
  'CrossmarkDomainExclusive': 'true',
  'DOI': '10.1016/j.imu.2019.100231',
  'MajorVersionDate': '2010-04-23'},
 'dc': {'creator': ['Sumaiya Dabeer', 'Maha Mohammed Khan', 'Saiful Islam'],
  'description': {'x-default': 'Informatics in Medicine Unlocked, 16 (2019) 100231. doi:10.1016/j.imu.2019.100231'},
  'format': 'application/pdf',
  'identifier': '10.1016/j.imu.2019.100231',
  'publisher': ['Elsevier Ltd'],
  'subject': ['Histopathology image',
   'Medical image processing',
   'Convolutional neural network',
   'Deep learning',
   'Breast cancer'],
  'title': {'x-default': 'Cancer diagnosis in histopathological image: CNN based approach'}},
 'http://prismstandard.org/namespaces/basic/3.0/': {'aggregationType': 'journal',
  'copyright': '© 2019 Published by Elsevier Ltd.',
  'coverDate': '2019',
  'coverDisplayDate': '21 December 2019',
  'doi': '10.1016/j.imu.2019.100231',
  'issn': '2352-9148',
  'pageRange': '100231',
  'publicationName': 'Informatics in Medicine Unlocked',
  'startingPage': '100231',
  'url': 'https://doi.org/10.1016/j.imu.2019.100231',
  'volume': '16'},
 'http://www.niso.org/schemas/ali/1.0/': {'license_ref': ['\n                  ']},
 'http://www.niso.org/schemas/jav/1.0/': {'journal_article_version': 'VoR'},
 'pdf': {'CreationDate--Text': '23rd December 2019',
  'Keywords': 'Histopathology image,Medical image processing,Convolutional neural network,Deep learning,Breast cancer',
  'Producer': 'Acrobat Distiller 8.1.0 (Windows)'},
 'pdfx': {'CreationDate--Text': '23rd December 2019',
  'CrossMarkDomains': ['sciencedirect.com', 'elsevier.com'],
  'CrossmarkDomainExclusive': 'true',
  'CrossmarkMajorVersionDate': '2010-04-23',
  'doi': '10.1016/j.imu.2019.100231',
  'robots': 'noindex'},
 'rights': {'Marked': 'True'},
 'xap': {'CreateDate': '2019-12-23T07:09:50',
  'CreatorTool': 'Elsevier',
  'MetadataDate': '2019-12-23T07:12:22',
  'ModifyDate': '2019-12-23T07:12:22'},
 'xapmm': {'DocumentID': 'uuid:1b499bed-4ce8-4c0c-b682-0d58baae1cbe',
  'InstanceID': 'uuid:b6ed5266-03cb-4855-90c0-636283357f42'}}

In [0]:
def get_all_values(d):
    if isinstance(d, dict):
        for v in d.values():
            yield from get_all_values(v)
    elif isinstance(d, list):
        for v in d:
            yield from get_all_values(v)
    else:
        yield d

values_list_1 = list(get_all_values(metadata_1))
values_list_2 = list(get_all_values(metadata_2))

In [0]:
id_1 = []
id_2 = []

for v in values_list_1 :
  if type(v) == str :
    if 'uuid' in v :
      id_1.append(v)

for v in values_list_2 :
  if type(v) == str :
    if 'uuid' in v :
      id_2.append(v)

docID_1 = id_1[0].lstrip('uuid:')
docID_2 = id_2[0].lstrip('uuid:')

In [125]:
docID_1

'95b96e2e-b2e0-4f2c-8345-72926bf336e7'

In [126]:
docID_2

'1b499bed-4ce8-4c0c-b682-0d58baae1cbe'

### Convert metadata to dataframe

In [0]:
import pandas as pd

add_meta_df_1 = pd.DataFrame.from_dict(metadata_1, orient='index')
add_meta_df_2 = pd.DataFrame.from_dict(metadata_2, orient='index')
#add_meta_df_3 = pd.DataFrame.from_dict(metadata_3, orient='index')

add_meta_df_1 = add_meta_df_1.transpose()
add_meta_df_2 = add_meta_df_2.transpose()
#add_meta_df_3 = add_meta_df_3.transpose()

#### Organize new metadata

In [128]:
add_meta_df_1

  CrossMarkDomains[2]  ... Pages
0        elsevier.com  ...     8

[1 rows x 23 columns]

In [130]:
add_meta_df_1[['journal','DOI']] = add_meta_df_1.Subject.str.split(",", expand=True)
sha = [docID_1]
add_meta_df_1['sha'] = sha
add_meta_df_1 = add_meta_df_1.rename(columns={'Title':'title', 'Author':'authors'})
add_meta_df_1 = add_meta_df_1[['sha', 'title', 'authors', 'doi', 'journal']]
add_meta_df_1

                                    sha  ...                                        journal
0  95b96e2e-b2e0-4f2c-8345-72926bf336e7  ...  Journal of Experimental and Clinical Medicine

[1 rows x 5 columns]

In [61]:
add_meta_df_2

    Creator  ... Pages
0  Elsevier  ...     9

[1 rows x 20 columns]

In [131]:
doi = []
for v in values_list_2 :
  if type(v) == str :
    if 'doi' in v :
      doi = v
      quit

doi = doi.lstrip('https://doi.org/')
doi

'10.1016/j.imu.2019.100231'

In [132]:
add_meta_df_2[['journal','etc']] = add_meta_df_2.Subject.str.split(",", expand=True)
sha = [docID_2]

add_meta_df_2['sha'] = sha
add_meta_df_2['doi'] = doi

add_meta_df_2 = add_meta_df_2.rename(columns={'Title':'title', 'Author':'authors'})
add_meta_df_2 = add_meta_df_2[['sha', 'title', 'authors', 'doi', 'journal']]
add_meta_df_2

                                    sha  ...                           journal
0  1b499bed-4ce8-4c0c-b682-0d58baae1cbe  ...  Informatics in Medicine Unlocked

[1 rows x 5 columns]

In [133]:
add_meta_df = add_meta_df_1.append(add_meta_df_2, ignore_index = True)
add_meta_df

                                    sha  ...                                        journal
0  95b96e2e-b2e0-4f2c-8345-72926bf336e7  ...  Journal of Experimental and Clinical Medicine
1  1b499bed-4ce8-4c0c-b682-0d58baae1cbe  ...               Informatics in Medicine Unlocked

[2 rows x 5 columns]

### Read original metadata.csv

In [134]:
metadata_path = 'metadata.csv'
meta_df = pd.read_csv(metadata_path, dtype={
    'pubmed_id': str,
    'Microsoft Academic Paper ID': str, 
    'doi': str
})
meta_df

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (14) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

       cord_uid  ...                                                url
0      zjufx4fo  ...  http://europepmc.org/articles/pmc125340?pdf=re...
1      ymceytj3  ...  http://europepmc.org/articles/pmc125375?pdf=re...
2      wzj2glte  ...  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1...
3      2sfqsfm1  ...  http://europepmc.org/articles/pmc126080?pdf=re...
4      i0zym7iq  ...  http://europepmc.org/articles/pmc136939?pdf=re...
...         ...  ...                                                ...
59882  pwq5gir9  ...         https://doi.org/10.1016/j.chom.2018.05.016
59883  3racv2qe  ...    https://doi.org/10.1016/j.neubiorev.2013.04.012
59884  jngto9kv  ...        https://doi.org/10.1016/j.medin.2011.01.001
59885  td0776wj  ...  https://doi.org/10.1016/b978-0-12-384890-1.000...
59886  jxbr6hbk  ...  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5...

[59887 rows x 19 columns]

### Add new metadata into original metadata

In [135]:
meta_df = meta_df.append(add_meta_df, ignore_index = True)
meta_df.tail()

       cord_uid  ...                                                url
59884  jngto9kv  ...        https://doi.org/10.1016/j.medin.2011.01.001
59885  td0776wj  ...  https://doi.org/10.1016/b978-0-12-384890-1.000...
59886  jxbr6hbk  ...  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5...
59887       NaN  ...                                                NaN
59888       NaN  ...                                                NaN

[5 rows x 19 columns]

In [136]:
meta_df.loc[meta_df['sha'] == '95b96e2e-b2e0-4f2c-8345-72926bf336e7']

      cord_uid                                   sha  ... full_text_file  url
59887      NaN  95b96e2e-b2e0-4f2c-8345-72926bf336e7  ...            NaN  NaN

[1 rows x 19 columns]

In [137]:
meta_df.loc[meta_df['sha'] == '1b499bed-4ce8-4c0c-b682-0d58baae1cbe']

      cord_uid                                   sha  ... full_text_file  url
59888      NaN  1b499bed-4ce8-4c0c-b682-0d58baae1cbe  ...            NaN  NaN

[1 rows x 19 columns]

In [0]:
meta_df.to_csv (r'new_meta.csv', index = False, header=True)

### Create JSON file

In [0]:
json_schema = {'paper_id': {"type" : "string"}, 
               'authors': {'first': "string"},
               'abstract': {"type" : "string"}, 
               'body_text': {"type" : "string"}}

In [0]:
text_1 = pdf_1.get_text()
text_2 = pdf_2.get_text()

In [0]:
file1 = open("paper1.txt","w")
  
# \n is placed to indicate EOL (End of Line) 
file1.write(text_1) 
file1.close()

In [0]:
file2 = open("paper2.txt","w")
  
# \n is placed to indicate EOL (End of Line) 
file2.write(text_2) 
file2.close()

In [0]:
with open('paper1.txt', 'r') as f1:
    t1 = f1.readlines()

with open('paper2.txt', 'r') as f2:
    t2 = f2.readlines()

In [86]:
print("paper1 text length : ", len(t1))
print("paper2 text length : ", len(t2))

paper1 text length :  1191
paper2 text length :  813

In [0]:
abstract_1 = t1[30:36]
abstract_2 = t2[20:30]

In [0]:
body_text_1 = t1[38:829]
body_text_2 = t2[31:658]

In [0]:
def listToDict(lst):
  text_lst = []
  for i in lst :
    op = { 'text' : i }
    text_lst.append(op)
  return text_lst

In [0]:
dict_abs_1 = listToDict(abstract_1)
dict_body_1 = listToDict(body_text_1)

dict_abs_2 = listToDict(abstract_2)
dict_body_2 = listToDict(body_text_2)

In [0]:
import json

json1 = {'paper_id' : docID_1,
         'authors' : {"first":add_meta_df_1['author'][0]},
         'abstract' : dict_abs_1,
         'body_text' : dict_body_1}

json2 = {'paper_id' : docID_2,
         'authors' : {"first":add_meta_df_2['author'][0]},
         'abstract' : dict_abs_2,
         'body_text' : dict_body_2}

with open('paper1.json', 'w') as outfile:
  json.dump(json1, outfile)

with open('paper2.json', 'w') as outfile:
  json.dump(json2, outfile)